language: node_js
node_js:
  - "0.8"
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - npm install -g bower
before_script:
  - npm install
  - ./test/bin/generate
  - sudo mv "${PWD}/test/temp" /vagrant
  - sudo /vagrant/bin/provision
