language: node_js
node_js:
  - "0.8"
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - sudo gem install  --no-rdoc --no-ri capistrano -v 2.15
  - sudo gem install  --no-rdoc --no-ri capistrano-ext colored
  - npm install -g bower
before_script:
  - echo "Running from ${PWD}"
  - npm install
  - "${PWD}/test/bin/mock"
  - ln -fs "${PWD}" "${PWD}/test/temp/bower_components/genesis-wordpress"
  - sudo mkdir -p /vagrant
  - sudo ln -s "${PWD}/test/temp/web" /vagrant/web
  - sudo "${PWD}/test/temp/bin/provision"
