language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
before_install:
  - rvm use 1.9.3
  - gem install bundler
  - echo "Install NPM dependencies"
  - npm install -g bower
  - npm install
  - echo "Mock test project"
  - $PWD/bin/mock
  - echo "Copy mock project to /vagrant for end-user tests"
  - sudo cp -R $PWD/temp /vagrant
  - echo "Symlinking local Genesis WordPress as dependency"
  - sudo rm -rf /vagrant/bower_components/genesis-skeleton
  - sudo cp -R $PWD /vagrant/bower_components/genesis-skeleton
  - echo "Install Composer dependencies"
  - echo "Provision server"
  - sudo $PWD/temp/bin/provision -e stage=localhost
  - curl -sS https://getcomposer.org/installer | php
install:
  - php composer.phar install --dev
script:
  - ./vendor/bin/phpunit
  - npm test
