language: node_js
node_js:
  - "0.8"
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - npm install -g bower
before_script:
  - npm install
  - ./test/bin/generate
  - sudo ln -s "${PWD}/test/temp" /vagrant
  - sudo ln -s "${PWD}" /wordpress
  - mkdir -p "${PWD}/bower_components"
  - sudo ln -s /wordpress "${PWD}/bower_components/genesis-wordpress"
  - sudo ./test/temp/bin/provision
