language: node_js
node_js:
  - "0.8"
  - "0.10"
hosts:
  - local.generatortest.com
install:
  - npm install -g bower
before_script:
  - npm install
  - ./test/support/generate
  - sudo mkdir /vagrant
  - sudo ln -s "${PWD}/test/temp/web" /vagrant/web
  - sudo ./test/temp/bin/provision
