language: node_js
node_js:
  - "0.8"
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - gem install capistrano -v 2.15
  - gem install capistrano-ext colored
  - npm install -g bower
before_script:
  - echo "Running from ${PWD}"
  - npm install
  - "${PWD}/test/bin/mock"
  - sudo mkdir -p /vagrant/web
  - sudo ln -s "${PWD}" /wordpress
  - sudo ln -s "${PWD}/test/temp/web" /vagrant/web
  - sudo "${PWD}/test/temp/bin/provision"
