language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
before_install:
  - rvm use 1.9.3
  - gem install bundler
  - npm install -g bower
  - echo "Install NPM dependencies"
  - npm install
  - echo "Mock test project"
  - $PWD/bin/mock
  - echo "Provision server"
  - sudo $PWD/temp/bin/provision -e stage=localhost
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=$PWD/temp
install:
  - cd $PWD/temp
  - bundle install
  - npm install
  - php composer.phar install --dev
script:
  - ./vendor/bin/phpunit
  - npm test
