language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - gem install  --no-rdoc --no-ri capistrano -v 2.15
  - gem install  --no-rdoc --no-ri capistrano-ext colored
  - npm install -g bower
before_script:
  - echo "Running from ${PWD}"
  - echo "Install NPM dependencies"
  - npm install
  - echo "Mock test project"
  - "${PWD}/test/bin/mock"
  - echo "Move mock project to /vagrant"
  - sudo mv "${PWD}/test/temp" /vagrant
  - echo "Remove Bower's Genesis WordPress"
  - rm -rf "/vagrant/bower_components/genesis-wordpress"
  - echo "Replace with this Genesis WordPress"
  - cp -R "${PWD}" /vagrant/bower_components/genesis-wordpress
  - echo "Provision server"
  - sudo /vagrant/bin/provision
