language: node_js
node_js:
  - "0.8"
  - "0.10"
hosts:
  - local.generatortest.com
install:
  - npm install -g bower
before_script:
  - cd ./test/support
  - ./generate
  - bower install
  - sudo ./bin/provision
