language: node_js
node_js:
  - "0.8"
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - npm install -g bower
  - gem install capistrano -v 2.15 capistrano-ext colored
before_script:
  - npm install
  - "${PWD}/test/bin/mock"
  - sudo ln -s "${PWD}/test/temp" /vagrant
  - sudo ln -s "${PWD}" /wordpress
  - mkdir -p "${PWD}/test/temp/bower_components"
  - ln -s /wordpress "${PWD}/test/temp/bower_components/genesis-wordpress"
  - sudo "${PWD}/test/temp/bin/provision"
