language: node_js
node_js:
  - "0.10"
addons:
  hosts:
    - local.generatortest.com
install:
  - gem install bundler
  - npm install -g bower
  - echo "PATH: $path"
before_script:
  - echo "Running from ${PWD}"
  - echo "Install NPM dependencies"
  - npm install
  - echo "Mock test project"
  - "${PWD}/test/bin/mock"
  - echo "Move mock project to /vagrant"
  - sudo mv "${PWD}/test/temp" /vagrant
  - echo "Provision server"
  - sudo /vagrant/bin/provision
